# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: Service # The name used to reference this repository in the checkout step
      type: github
      endpoint: surveyjs
      name: surveyjs/service

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
- checkout: Service
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    cd $(Build.SourcesDirectory)/survey-pdf
    npm install
  displayName: 'npm install'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '7'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSLibraryBuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages/survey-core'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-pdf/node_modules/survey-core'
    OverWrite: true

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
    pipeline: '42'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'SurveyJSWidgetsBuild'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSWidgetsBuild/packages/survey-widgets'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/survey-pdf/node_modules/surveyjs-widgets'
    OverWrite: true

- script: |
    cd $(Build.SourcesDirectory)/survey-pdf
    npm run build_prod
  displayName: 'build'

- script: |
    cd $(Build.SourcesDirectory)/survey-pdf
    npm test
  displayName: 'unit tests'

- script: |
    cd $(Build.SourcesDirectory)/survey-pdf
    npm run doc_gen
  displayName: 'generate docs'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/survey-pdf/docs'
    TargetFolder: '$(Build.SourcesDirectory)/service/surveyjs.io/App_Data/DocsPdf'
    CleanTargetFolder: true
  displayName: 'copy generated docs to the local surveyjs/service repo'

# read about the problem with git output ($env:GIT_REDIRECT_STDERR = '2>&1') :
# https://github.com/microsoft/azure-pipelines-yaml/issues/248
# https://stackoverflow.com/questions/58485585/azure-pipeline-powershell-and-git-on-windows-server-2019-gives-error-in-output
- powershell: |
    cd $(Build.SourcesDirectory)/service
    $env:GIT_REDIRECT_STDERR = '2>&1'
    git config --global user.email "kurmanov.work@gmail.com"
    git config --global user.name "dmitrykurmanov"
    git checkout master
    git pull origin master
    git fetch --tags --force
    git add surveyjs.io/App_Data/DocsPdf
    git commit -m "[skip ci] Updated survey-pdf docs"
    git pull origin master
    git push origin master
  displayName: 'git surveyjs/service push updated docs'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/survey-pdf/packages/survey-pdf'
    targetFolder: $(Build.ArtifactStagingDirectory)/packages/survey-pdf

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SurveyjsPDFbuild'
    publishLocation: 'Container'